# Generated by Django 5.2.3 on 2025-06-12 02:12

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emph_app', '0002_client_country_client_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('CLIENT', 'Client')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
